//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsClient.SampleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SampleService.ISampleService")]
    public interface ISampleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/RequestReplyOperation", ReplyAction="http://tempuri.org/ISampleService/RequestReplyOperationResponse")]
        string RequestReplyOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/RequestReplyOperation", ReplyAction="http://tempuri.org/ISampleService/RequestReplyOperationResponse")]
        System.Threading.Tasks.Task<string> RequestReplyOperationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/RequestReplyOperation_ThrowsException", ReplyAction="http://tempuri.org/ISampleService/RequestReplyOperation_ThrowsExceptionResponse")]
        string RequestReplyOperation_ThrowsException();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleService/RequestReplyOperation_ThrowsException", ReplyAction="http://tempuri.org/ISampleService/RequestReplyOperation_ThrowsExceptionResponse")]
        System.Threading.Tasks.Task<string> RequestReplyOperation_ThrowsExceptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISampleService/OneWayOperation")]
        void OneWayOperation();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISampleService/OneWayOperation")]
        System.Threading.Tasks.Task OneWayOperationAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISampleService/OneWayOperation_ThrowsException")]
        void OneWayOperation_ThrowsException();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISampleService/OneWayOperation_ThrowsException")]
        System.Threading.Tasks.Task OneWayOperation_ThrowsExceptionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleServiceChannel : WindowsClient.SampleService.ISampleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleServiceClient : System.ServiceModel.ClientBase<WindowsClient.SampleService.ISampleService>, WindowsClient.SampleService.ISampleService {
        
        public SampleServiceClient() {
        }
        
        public SampleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RequestReplyOperation() {
            return base.Channel.RequestReplyOperation();
        }
        
        public System.Threading.Tasks.Task<string> RequestReplyOperationAsync() {
            return base.Channel.RequestReplyOperationAsync();
        }
        
        public string RequestReplyOperation_ThrowsException() {
            return base.Channel.RequestReplyOperation_ThrowsException();
        }
        
        public System.Threading.Tasks.Task<string> RequestReplyOperation_ThrowsExceptionAsync() {
            return base.Channel.RequestReplyOperation_ThrowsExceptionAsync();
        }
        
        public void OneWayOperation() {
            base.Channel.OneWayOperation();
        }
        
        public System.Threading.Tasks.Task OneWayOperationAsync() {
            return base.Channel.OneWayOperationAsync();
        }
        
        public void OneWayOperation_ThrowsException() {
            base.Channel.OneWayOperation_ThrowsException();
        }
        
        public System.Threading.Tasks.Task OneWayOperation_ThrowsExceptionAsync() {
            return base.Channel.OneWayOperation_ThrowsExceptionAsync();
        }
    }
}
